export interface Task {
  id: string;          // generated by code
  title: string;       // from taskTitle field
  description: string; // from description field
  priority: 'low' | 'medium' | 'high';  // from status field
  status: 'todo' | 'in-progress' | 'done'; // always 'todo' at creation
  createdAt: Date;     // generated by code
}

export interface taskCount{
    total:number;
    pending:number;
    done:number;
}